version: "3"
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/.cache/
    npm:
        image: node:18
        volumes:
            - ..:/usr/src/app
            - /usr/src/app/node_modules/
        working_dir: /usr/src/app
        stdin_open: true
        tty: true
        command: "npm init -y"
